#!/bin/bash

export OPENCL_INC_PATH=/usr/include
export HMPPRT_NO_FALLBACK=1
export ACC_DEVICE_TYPE=acc_device_opencl
export HMPPRT_OPENCL_DEVICE_TYPE=CL_DEVICE_TYPE_ACCELERATOR
#GRID_X=(2 32 1 64 8 16 4 32 2 64 1 128 16 8 32 4 64 2 128 1 256 32 16 8 64 2 256)
#GRID_Y=(32 2 64 1 16 8 32 4 64 2 128 1 16 32 8 64 4 128 2 256 1 16 32 64 8 256 2)

GRID_X=(16 32 64 16 32 64 128 16 32 64 128 256 32 64 256 512)
GRID_Y=(4 2 1 8 4 2 1 16 8 4 2 1 16 8 2 1)
for INPUT in 20971520 
do
	echo "============================" $INPUT "======================================"
                for (( i = 0 ; i < ${#GRID_X[@]} ; i++ ))
	 	do
			echo "------------------------------------------------------------"
			echo ${GRID_X[$i]} x ${GRID_Y[$i]}
			make GRIDX=${GRID_X[$i]} GRIDY=${GRID_Y[$i]}
			./backprop ${INPUT}
			make clean
		done
done




